# Generated by Django 4.2.5 on 2025-05-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_review_wishlist_reviewimage_productvideo_and_more'),
    ]

    operations = [
    ]
