# Generated by Django 4.2.5 on 2025-05-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_initial_products'),
    ]

    operations = [
    ]
