# Generated by Django 4.2.5 on 2025-05-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_initial_products'),
    ]

    operations = [
    ]
