# Generated by Django 4.2.5 on 2025-05-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_initial_accounts'),
    ]

    operations = [
    ]
