# Generated by Django 4.2.5 on 2025-05-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_initial_accounts'),
    ]

    operations = [
    ]
