# Generated by Django 4.2.5 on 2025-05-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_initial_accounts'),
    ]

    operations = [
    ]
