# Generated by Django 4.2.5 on 2025-05-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0004_initial_user_activity'),
    ]

    operations = [
    ]
