# Generated by Django 4.2.5 on 2025-05-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0007_initial_user_activity'),
    ]

    operations = [
    ]
