# Generated by Django 4.2.5 on 2025-05-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0013_initial_user_activity'),
    ]

    operations = [
    ]
