# Generated by Django 4.2.5 on 2025-05-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_cart_review_wishlist_reviewimage_productvideo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='Запрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос к ИИ',
                'verbose_name_plural': 'Запросы к ИИ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('products', models.ManyToManyField(related_name='ai_recommendations', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ИИ-рекомендация',
                'verbose_name_plural': 'ИИ-рекомендации',
                'ordering': ['-created_at'],
            },
        ),
    ]
