# Generated by Django 4.2.5 on 2025-05-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_status', 'Статус заказа'), ('chat_message', 'Сообщение в чате'), ('product_change', 'Изменение товара'), ('system', 'Системное')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_updates', models.BooleanField(default=True, verbose_name='Обновления заказов')),
                ('new_messages', models.BooleanField(default=True, verbose_name='Новые сообщения')),
                ('product_updates', models.BooleanField(default=True, verbose_name='Обновления товаров')),
                ('promotions', models.BooleanField(default=True, verbose_name='Акции и скидки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки email-уведомлений',
                'verbose_name_plural': 'Настройки email-уведомлений',
            },
        ),
    ]
